"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["ARPHRDType"]


class ARPHRDType(IntEnum):
    ETHER = 1
    NONE = 65534
    LOOPBACK = 772

    @property
    def constant_name(self) -> str:
        return f"ARPHRD_{self.name}"
