"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["CtrlAttr"]


class CtrlAttr(IntEnum):
    UNSPEC: Final = 0
    FAMILY_ID: Final = 1
    FAMILY_NAME: Final = 2
    VERSION: Final = 3
    HDRSIZE: Final = 4
    MAXATTR: Final = 5
    OPS: Final = 6
    MCAST_GROUPS: Final = 7

    @property
    def constant_name(self) -> str:
        return f"CTRL_ATTR_{self.name}"
