# This file was generated by gen_constants.py
from enum import IntEnum
from typing import Final

__all__ = ["CtrlCmd"]


class CtrlCmd(IntEnum):        
    UNSPEC: Final = 0
    NEWFAMILY: Final = 1
    DELFAMILY: Final = 2
    GETFAMILY: Final = 3
    NEWOPS: Final = 4
    DELOPS: Final = 5
    GETOPS: Final = 6
    NEWMCAST_GRP: Final = 7
    DELMCAST_GRP: Final = 8
    GETMCAST_GRP: Final = 9

    @property
    def constant_name(self) -> str:
        return f"CTRL_CMD_{self.name}"

