"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["FRAType"]


class FRAType(IntEnum):
    UNSPEC = 0
    DST = 1
    SRC = 2
    IIFNAME = 3
    GOTO = 4
    UNUSED2 = 5
    PRIORITY = 6
    UNUSED3 = 7
    UNUSED4 = 8
    UNUSED5 = 9
    FWMARK = 10
    FLOW = 11
    TUN_ID = 12
    SUPPRESS_IFGROUP = 13
    SUPPRESS_PREFIXLEN = 14
    TABLE = 15
    FWMASK = 16
    OIFNAME = 17
    PAD = 18
    L3MDEV = 19
    UID_RANGE = 20
    PROTOCOL = 21
    IP_PROTO = 22
    SPORT_RANGE = 23
    DPORT_RANGE = 24

    @property
    def constant_name(self) -> str:
        return f"FRA_{self.name}"
