# This file was generated by gen_constants.py
from enum import IntEnum
from typing import Final

__all__ = ["FRAType"]


class FRAType(IntEnum):        
    UNSPEC: Final = 0
    DST: Final = 1
    SRC: Final = 2
    IIFNAME: Final = 3
    GOTO: Final = 4
    UNUSED2: Final = 5
    PRIORITY: Final = 6
    UNUSED3: Final = 7
    UNUSED4: Final = 8
    UNUSED5: Final = 9
    FWMARK: Final = 10
    FLOW: Final = 11
    TUN_ID: Final = 12
    SUPPRESS_IFGROUP: Final = 13
    SUPPRESS_PREFIXLEN: Final = 14
    TABLE: Final = 15
    FWMASK: Final = 16
    OIFNAME: Final = 17
    PAD: Final = 18
    L3MDEV: Final = 19
    UID_RANGE: Final = 20
    PROTOCOL: Final = 21
    IP_PROTO: Final = 22
    SPORT_RANGE: Final = 23
    DPORT_RANGE: Final = 24

    @property
    def constant_name(self) -> str:
        return f"FRA_{self.name}"

