"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["ICMPv6RouterPref"]


class ICMPv6RouterPref(IntEnum):
    LOW: Final = 3
    MEDIUM: Final = 0
    HIGH: Final = 1
    INVALID: Final = 2

    @property
    def constant_name(self) -> str:
        return f"ICMPV6_ROUTER_PREF_{self.name}"
