"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["ICMPv6RouterPref"]


class ICMPv6RouterPref(IntEnum):
    LOW = 3
    MEDIUM = 0
    HIGH = 1
    INVALID = 2

    @property
    def constant_name(self) -> str:
        return f"ICMPV6_ROUTER_PREF_{self.name}"
