"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["IFAFlag"]


class IFAFlag(IntEnum):
    SECONDARY = 1 << 0
    NODAD = 1 << 1
    OPTIMISTIC = 1 << 2
    DADFAILED = 1 << 3
    HOMEADDRESS = 1 << 4
    DEPRECATED = 1 << 5
    TENTATIVE = 1 << 6
    PERMANENT = 1 << 7
    MANAGETEMPADDR = 1 << 8
    NOPREFIXROUTE = 1 << 9
    MCAUTOJOIN = 1 << 10
    STABLE_PRIVACY = 1 << 11

    @property
    def constant_name(self) -> str:
        return f"IFA_F_{self.name}"
