"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["IFAType"]


class IFAType(IntEnum):
    UNSPEC = 0
    ADDRESS = 1
    LOCAL = 2
    LABEL = 3
    BROADCAST = 4
    ANYCAST = 5
    CACHEINFO = 6
    MULTICAST = 7
    FLAGS = 8
    RT_PRIORITY = 9
    TARGET_NETNSID = 10
    PROTO = 11

    @property
    def constant_name(self) -> str:
        return f"IFA_{self.name}"
