# This file was generated by gen_constants.py
from enum import IntEnum
from typing import Final

__all__ = ["IFAType"]


class IFAType(IntEnum):        
    UNSPEC: Final = 0
    ADDRESS: Final = 1
    LOCAL: Final = 2
    LABEL: Final = 3
    BROADCAST: Final = 4
    ANYCAST: Final = 5
    CACHEINFO: Final = 6
    MULTICAST: Final = 7
    FLAGS: Final = 8
    RT_PRIORITY: Final = 9
    TARGET_NETNSID: Final = 10
    PROTO: Final = 11

    @property
    def constant_name(self) -> str:
        return f"IFA_{self.name}"

