"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["IFLAType"]


class IFLAType(IntEnum):
    UNSPEC: Final = 0
    ADDRESS: Final = 1
    BROADCAST: Final = 2
    IFNAME: Final = 3
    MTU: Final = 4
    LINK: Final = 5
    QDISC: Final = 6
    STATS: Final = 7
    COST: Final = 8
    PRIORITY: Final = 9
    MASTER: Final = 10
    WIRELESS: Final = 11
    PROTINFO: Final = 12
    TXQLEN: Final = 13
    MAP: Final = 14
    WEIGHT: Final = 15
    OPERSTATE: Final = 16
    LINKMODE: Final = 17
    LINKINFO: Final = 18
    NET_NS_PID: Final = 19
    IFALIAS: Final = 20
    NUM_VF: Final = 21
    VFINFO_LIST: Final = 22
    STATS64: Final = 23
    VF_PORTS: Final = 24
    PORT_SELF: Final = 25
    AF_SPEC: Final = 26
    GROUP: Final = 27
    NET_NS_FD: Final = 28
    EXT_MASK: Final = 29
    PROMISCUITY: Final = 30
    NUM_TX_QUEUES: Final = 31
    NUM_RX_QUEUES: Final = 32
    CARRIER: Final = 33
    PHYS_PORT_ID: Final = 34
    CARRIER_CHANGES: Final = 35
    PHYS_SWITCH_ID: Final = 36
    LINK_NETNSID: Final = 37
    PHYS_PORT_NAME: Final = 38
    PROTO_DOWN: Final = 39

    @property
    def constant_name(self) -> str:
        return f"IFLA_{self.name}"
