"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["IFLAType"]


class IFLAType(IntEnum):
    UNSPEC = 0
    ADDRESS = 1
    BROADCAST = 2
    IFNAME = 3
    MTU = 4
    LINK = 5
    QDISC = 6
    STATS = 7
    COST = 8
    PRIORITY = 9
    MASTER = 10
    WIRELESS = 11
    PROTINFO = 12
    TXQLEN = 13
    MAP = 14
    WEIGHT = 15
    OPERSTATE = 16
    LINKMODE = 17
    LINKINFO = 18
    NET_NS_PID = 19
    IFALIAS = 20
    NUM_VF = 21
    VFINFO_LIST = 22
    STATS64 = 23
    VF_PORTS = 24
    PORT_SELF = 25
    AF_SPEC = 26
    GROUP = 27
    NET_NS_FD = 28
    EXT_MASK = 29
    PROMISCUITY = 30
    NUM_TX_QUEUES = 31
    NUM_RX_QUEUES = 32
    CARRIER = 33
    PHYS_PORT_ID = 34
    CARRIER_CHANGES = 35
    PHYS_SWITCH_ID = 36
    LINK_NETNSID = 37
    PHYS_PORT_NAME = 38
    PROTO_DOWN = 39

    @property
    def constant_name(self) -> str:
        return f"IFLA_{self.name}"
