"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["IFLinkMode"]


class IFLinkMode(IntEnum):
    DEFAULT: Final = 0x0
    DORMANT: Final = 1 << 0
    TESTING: Final = 1 << 1

    @property
    def constant_name(self) -> str:
        return f"IF_LINK_MODE_{self.name}"
