"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["IFLinkMode"]


class IFLinkMode(IntEnum):
    DEFAULT = 0x0
    DORMANT = 1 << 0
    TESTING = 1 << 1

    @property
    def constant_name(self) -> str:
        return f"IF_LINK_MODE_{self.name}"
