"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["IFOper"]


class IFOper(IntEnum):
    UNKNOWN = 0x0
    NOTPRESENT = 1 << 0
    DOWN = 1 << 1
    LOWERLAYERDOWN = 0x3
    TESTING = 1 << 2
    DORMANT = 0x5
    UP = 0x6

    @property
    def constant_name(self) -> str:
        return f"IF_OPER_{self.name}"
