# This file was generated by gen_constants.py
from enum import IntEnum
from typing import Final

__all__ = ["NLFamily"]


class NLFamily(IntEnum):
    ROUTE: Final = 0
    USERSOCK: Final = 2
    FIREWALL: Final = 3
    SOCK_DIAG: Final = 4
    INET_DIAG: Final = 4
    NFLOG: Final = 5
    XFRM: Final = 6
    SELINUX: Final = 7
    ISCSI: Final = 8
    AUDIT: Final = 9
    FIB_LOOKUP: Final = 10
    CONNECTOR: Final = 11
    NETFILTER: Final = 12
    IP6_FW: Final = 13
    DNRTMSG: Final = 14
    KOBJECT_UEVENT: Final = 15
    GENERIC: Final = 16
    CRYPTO: Final = 21

    @property
    def constant_name(self) -> str:
        return f"NETLINK_{self.name}"
