"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["NLMsgType"]


class NLMsgType(IntEnum):
    NOOP = 1
    ERROR = 2
    DONE = 3
    OVERRUN = 4
    MIN_TYPE = 16

    @property
    def constant_name(self) -> str:
        return f"NLMSG_{self.name}"
