"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTAType"]


class RTAType(IntEnum):
    UNSPEC = 0
    DST = 1
    SRC = 2
    IIF = 3
    OIF = 4
    GATEWAY = 5
    PRIORITY = 6
    PREFSRC = 7
    METRICS = 8
    MULTIPATH = 9
    PROTOINFO = 10
    FLOW = 11
    CACHEINFO = 12
    SESSION = 13
    MP_ALGO = 14
    TABLE = 15
    MARK = 16
    MFC_STATS = 17
    VIA = 18
    NEWDST = 19
    PREF = 20
    ENCAP_TYPE = 21
    ENCAP = 22
    EXPIRES = 23
    PAD = 24
    UID = 25
    TTL_PROPAGATE = 26
    IP_PROTO = 27
    SPORT = 28
    DPORT = 29
    NH_ID = 30

    @property
    def constant_name(self) -> str:
        return f"RTA_{self.name}"
