"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTCFlag"]


class RTCFlag(IntEnum):
    DEAD = 1 << 0
    ONLINK = 1 << 2
    NOTIFY = 1 << 16
    DIRECTDST = 1 << 17
    REDIRECTED = 1 << 18
    TPROXY = 1 << 19
    FAST = 1 << 21
    MASQ = 1 << 22
    SNAT = 1 << 23
    DOREDIRECT = 1 << 24
    DIRECTSRC = 1 << 26
    DNAT = 1 << 27
    BROADCAST = 1 << 28
    MULTICAST = 1 << 29
    REJECT = 1 << 30
    LOCAL = 1 << 31

    @property
    def constant_name(self) -> str:
        return f"RTCF_{self.name}"
