"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["RTCFlag"]


class RTCFlag(IntEnum):
    DEAD: Final = 1 << 0
    ONLINK: Final = 1 << 2
    NOTIFY: Final = 1 << 16
    DIRECTDST: Final = 1 << 17
    REDIRECTED: Final = 1 << 18
    TPROXY: Final = 1 << 19
    FAST: Final = 1 << 21
    MASQ: Final = 1 << 22
    SNAT: Final = 1 << 23
    DOREDIRECT: Final = 1 << 24
    DIRECTSRC: Final = 1 << 26
    DNAT: Final = 1 << 27
    BROADCAST: Final = 1 << 28
    MULTICAST: Final = 1 << 29
    REJECT: Final = 1 << 30
    LOCAL: Final = 1 << 31

    @property
    def constant_name(self) -> str:
        return f"RTCF_{self.name}"
