"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["RTMFlag"]


class RTMFlag(IntEnum):
    NOTIFY: Final = 1 << 8
    CLONED: Final = 1 << 9
    EQUALIZE: Final = 1 << 10

    @property
    def constant_name(self) -> str:
        return f"RTM_F_{self.name}"
