"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTMFlag"]


class RTMFlag(IntEnum):
    NOTIFY = 1 << 8
    CLONED = 1 << 9
    EQUALIZE = 1 << 10

    @property
    def constant_name(self) -> str:
        return f"RTM_F_{self.name}"
