"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["RTMType"]


class RTMType(IntEnum):
    NEWLINK: Final = 16
    DELLINK: Final = 17
    GETLINK: Final = 18
    SETLINK: Final = 19
    NEWADDR: Final = 20
    DELADDR: Final = 21
    GETADDR: Final = 22
    NEWROUTE: Final = 24
    DELROUTE: Final = 25
    GETROUTE: Final = 26
    NEWNEIGH: Final = 28
    DELNEIGH: Final = 29
    GETNEIGH: Final = 30
    NEWRULE: Final = 32
    DELRULE: Final = 33
    GETRULE: Final = 34
    NEWQDISC: Final = 36
    DELQDISC: Final = 37
    GETQDISC: Final = 38
    NEWTCLASS: Final = 40
    DELTCLASS: Final = 41
    GETTCLASS: Final = 42
    NEWTFILTER: Final = 44
    DELTFILTER: Final = 45
    GETTFILTER: Final = 46
    NEWACTION: Final = 48
    DELACTION: Final = 49
    GETACTION: Final = 50
    NEWPREFIX: Final = 52
    GETMULTICAST: Final = 58
    GETANYCAST: Final = 62
    NEWNEIGHTBL: Final = 64
    GETNEIGHTBL: Final = 66
    SETNEIGHTBL: Final = 67
    NEWNDUSEROPT: Final = 68
    NEWADDRLABEL: Final = 72
    DELADDRLABEL: Final = 73
    GETADDRLABEL: Final = 74
    GETDCB: Final = 78
    SETDCB: Final = 79

    @property
    def constant_name(self) -> str:
        return f"RTM_{self.name}"
