"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTNLGroup"]


class RTNLGroup(IntEnum):
    NONE = 0
    LINK = 1
    NOTIFY = 2
    NEIGH = 3
    TC = 4
    IPV4_IFADDR = 5
    IPV4_MROUTE = 6
    IPV4_ROUTE = 7
    IPV4_RULE = 8
    IPV6_IFADDR = 9
    IPV6_MROUTE = 10
    IPV6_ROUTE = 11
    IPV6_IFINFO = 12
    DECnet_IFADDR = 13
    NOP2 = 14
    DECnet_ROUTE = 15
    DECnet_RULE = 16
    NOP4 = 17
    IPV6_PREFIX = 18
    IPV6_RULE = 19
    ND_USEROPT = 20
    PHONET_IFADDR = 21
    PHONET_ROUTE = 22

    @property
    def constant_name(self) -> str:
        return f"RTNLGRP_{self.name}"
