"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTNLFamily"]


class RTNLFamily(IntEnum):
    IPMR = 128
    IP6MR = 129

    @property
    def constant_name(self) -> str:
        return f"RTNL_FAMILY_{self.name}"
