"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTNType"]


class RTNType(IntEnum):
    UNSPEC = 0
    UNICAST = 1
    LOCAL = 2
    BROADCAST = 3
    ANYCAST = 4
    MULTICAST = 5
    BLACKHOLE = 6
    UNREACHABLE = 7
    PROHIBIT = 8
    THROW = 9
    NAT = 10
    XRESOLVE = 11

    @property
    def constant_name(self) -> str:
        return f"RTN_{self.name}"
