"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTProt"]


class RTProt(IntEnum):
    UNSPEC = 0
    REDIRECT = 1
    KERNEL = 2
    BOOT = 3
    STATIC = 4

    @property
    def constant_name(self) -> str:
        return f"RTPROT_{self.name}"
