"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["RTProt"]


class RTProt(IntEnum):
    UNSPEC: Final = 0
    REDIRECT: Final = 1
    KERNEL: Final = 2
    BOOT: Final = 3
    STATIC: Final = 4

    @property
    def constant_name(self) -> str:
        return f"RTPROT_{self.name}"
