"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTScope"]


class RTScope(IntEnum):
    UNIVERSE = 0
    SITE = 200
    LINK = 253
    HOST = 254
    NOWHERE = 255

    @property
    def constant_name(self) -> str:
        return f"RT_SCOPE_{self.name}"
