"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["RTScope"]


class RTScope(IntEnum):
    UNIVERSE: Final = 0
    SITE: Final = 200
    LINK: Final = 253
    HOST: Final = 254
    NOWHERE: Final = 255

    @property
    def constant_name(self) -> str:
        return f"RT_SCOPE_{self.name}"
