"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["RTTable"]


class RTTable(IntEnum):
    UNSPEC: Final = 0
    DEFAULT: Final = 253
    MAIN: Final = 254
    LOCAL: Final = 255

    @property
    def constant_name(self) -> str:
        return f"RT_TABLE_{self.name}"
