"""
This file was generated by gen_constants.py
"""

from enum import IntEnum

__all__ = ["RTTable"]


class RTTable(IntEnum):
    UNSPEC = 0
    DEFAULT = 253
    MAIN = 254
    LOCAL = 255

    @property
    def constant_name(self) -> str:
        return f"RT_TABLE_{self.name}"
