# This file was generated by gen_constants.py
from enum import IntEnum
from typing import Final

__all__ = ["TunIoctl"]


class TunIoctl(IntEnum):        
    SETNOCSUM: Final = 0x400454c8
    SETDEBUG: Final = 0x400454c9
    SETIFF: Final = 0x400454ca
    SETPERSIST: Final = 0x400454cb
    SETOWNER: Final = 0x400454cc
    SETLINK: Final = 0x400454cd
    SETGROUP: Final = 0x400454ce
    GETFEATURES: Final = 0x800454cf
    SETOFFLOAD: Final = 0x400454d0
    SETTXFILTER: Final = 0x400454d1
    GETIFF: Final = 0x800454d2
    GETSNDBUF: Final = 0x800454d3
    SETSNDBUF: Final = 0x400454d4
    ATTACHFILTER: Final = 0x401054d5
    DETACHFILTER: Final = 0x401054d6
    GETVNETHDRSZ: Final = 0x800454d7
    SETVNETHDRSZ: Final = 0x400454d8
    SETVNETBE: Final = 0x400454de
    GETVNETBE: Final = 0x800454df
    SETSTEERINGEBPF: Final = 0x800454e0
    SETFILTEREBPF: Final = 0x800454e1
    SETCARRIER: Final = 0x400454e2
    GETDEVNETNS: Final = 0x54e3

    @property
    def constant_name(self) -> str:
        return f"TUN{self.name}"

