"""
This file was generated by gen_constants.py
"""

from enum import IntEnum
from typing import Final

__all__ = ["TunIoctl"]


class TunIoctl(IntEnum):
    SETNOCSUM: Final = 0x400454C8
    SETDEBUG: Final = 0x400454C9
    SETIFF: Final = 0x400454CA
    SETPERSIST: Final = 0x400454CB
    SETOWNER: Final = 0x400454CC
    SETLINK: Final = 0x400454CD
    SETGROUP: Final = 0x400454CE
    GETFEATURES: Final = 0x800454CF
    SETOFFLOAD: Final = 0x400454D0
    SETTXFILTER: Final = 0x400454D1
    GETIFF: Final = 0x800454D2
    GETSNDBUF: Final = 0x800454D3
    SETSNDBUF: Final = 0x400454D4
    ATTACHFILTER: Final = 0x401054D5
    DETACHFILTER: Final = 0x401054D6
    GETVNETHDRSZ: Final = 0x800454D7
    SETVNETHDRSZ: Final = 0x400454D8
    SETVNETBE: Final = 0x400454DE
    GETVNETBE: Final = 0x800454DF
    SETSTEERINGEBPF: Final = 0x800454E0
    SETFILTEREBPF: Final = 0x800454E1
    SETCARRIER: Final = 0x400454E2
    GETDEVNETNS: Final = 0x54E3

    @property
    def constant_name(self) -> str:
        return f"TUN{self.name}"
